server:
  port: 8080
spring:
  application:
    name: "mutants-test"
  devtools:
    add-properties: false
  profiles:
    include: null
  data:
    mongodb:
      uri: "<MONGODB_URL_NOT_LOCAL>"
      database: <DATABASE_NAME>
