server:
  port: 8080
spring:
  application:
    name: "mutants-test"
  devtools:
    add-properties: false
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://$MONGODB_USERNAME:$MONGODB_PASSWORD@testingcluster.jhwos.mongodb.net/?retryWrites=true&w=majority"
      database: MeLiTest
